### ISSUE TITLE
Allow Curate ND to read items stored in Bendo

### ISSUE THREAD

**Issue by msuhovec** [ndlib/curate_nd#298]
When Content is being stored in Bendo, Fedora will provide a link to it via an R ('redirect datastream) DataStream. Curate ND will need to be changed to accommodate this.

- [x] Allow files to be downloaded from Bendo via Disadis
- [x] Display the cache status on for files on the work show view
  - [x] Build an API endpoint in CurateND for interacting with the [Bendo API](https://github.com/ndlib/bendo/blob/api-docs/architecture/api.md)
     - [x] Query the cache status of one or more items
       - [x] Implement API calls to Bendo
     - [x] Warm the cache for one item
       - [x] Implement API calls to Bendo
  - [x] Write JavaScript that queries the cache status API
    - [x] Toggle download button state between “Recall Item” and “Download” based on cache status
    - [x] Display file access notice based on cache status
    - [x] Toggle access URLs between `/download/:pid` and `/recall/:pid` based on cache status
  - [x] Implement “retrieval” behavior
    - [x] Display notice on placeholder page
    - [x] Display file size (based on FITS on placeholder page)
    - [x] Call Bendo API to recall item
    - [x] Implement cache status poller that will redirect to the download URL when finished

---
See #425 for updating items stored in Bendo

**Comment by danhorst** [comment]
@dbrower @jeremyf this was my takeaway from our discussion:
![download-logic](https://cloud.githubusercontent.com/assets/2133/15589557/713531de-2361-11e6-853d-d57e069cf47e.png)

What did I get wrong?

**Comment by dbrower** [comment]
This seems largely correct.

I will point out that there may be reasons you wouldn't want to redirect the client to the dsLocation (mainly because of firewalls). You may want to just ignore whether it is an R datastream for download purposes: The libvirt9 machine seems to be working ok without any special handling of R datastreams---it treats them the same as M datastreams since rubydora will automatically follow 301s from fedora. I have not gone through the code thoroughly and I'm unsure everything is hunky-dory.

However, you will **want** to know whether it is an R datastream to display a label that it is on tape. I tried to download something on libvirt9 which had gotten paged off to tape and the first attempt timed out after 30 seconds (but the second a few minutes later worked fine).

**Comment by danhorst** [comment]
@dbrower the “DL proxy enabled?” decision point is controlled via the `use_proxy_for_download` flag in the rails environment config. It is enabled in [staging](https://github.com/ndlib/curate_nd/blob/master/config/environments/staging.rb#L59), [pre-production](https://github.com/ndlib/curate_nd/blob/master/config/environments/pre_production.rb#L88), and [production](https://github.com/ndlib/curate_nd/blob/master/config/environments/production.rb#L88).

The ability to simply redirect to the datastream content was useful for me as it allowed me to test it in development without having to run [disadis](https://github.com/ndlib/disadis).

---

How should we communicate that a file may take several minutes to load? Is a label on the page sufficient?

![curatend-298-badge-for-archival-storage-cropped](https://cloud.githubusercontent.com/assets/2133/15594117/90194cd8-2380-11e6-9362-eeb2c2c73731.png)

or do we need some sort of intermediate loading page?

![curatend-298-retrieval-notice-cropped](https://cloud.githubusercontent.com/assets/2133/15594252/e6646112-2381-11e6-8978-a9a323da98c8.png)

Do you have an opinion @ruthtillman?

**Comment by ruthtillman** [comment]
Generally I'm not a fan of interim loading pages when we don't have to.

I think what I'd like is the label flag (with adequate spacing on the object, of course), but I would like for there to be a contextual textual note directly below Files if possible. Two sentences or so along the lines of:

"CurateND can archive large data files. Files labeled as "On Tape" are larger than [ @dbrower insert size here ] and may take some time to download as they are retrieved from tape storage."

...I know it's not perfect but I think it frames as at least somewhat positive "Hey look,we can handle large files!"

This is all assuming that the only objects flagged as "on tape" are objects which are not in some sort of cache and that other objects are in some sort of cache. Is this the case?

**Comment by dbrower** [comment]
I like the "on tape" indication...you can query bendo and see if things are cached or not. I would change the "on tape" indication to be below the access control and to either be missing (if it is cached) or be present and consist of some text saying "This item is on tape and will take a few minutes to retrieve." or some such.

If an item is on tape and a user clicked a download link, there is a good chance the download will time out since nginx caps requests to 60 seconds if there is no data transfer. So the user will get a timeout error, and at some point the item will be cached and will then download with no problems.

So...thinking this through while I'm typing, perhaps if something is on tape the download button should instead read "request retrieval". but then what would clicking on the link do? Return an error? There was a hydra-tech thread about this behavior from march. need to find it.

ok, but before finding the thread, maybe there are two links: `/download/{pid}` and `recall/{pid}`. the latter will just cache the item, but doesn't return errors (unless the pid is invalid), and doesn't wait for the item to be cached. The former will wait and return the content, possibly timing out if the content is not cached. Just thoughts.

**Comment by ruthtillman** [comment]
I'm ok with the display idea but the timeout thing is... hmm, yeah... that's definitely something to mitigate... "request retrieval" makes more sense if they're not actually going to be able to download it...

**Comment by danhorst** [comment]
UI update:
If all files are cached in Bendo or are stored in Fedora:
![curatend-298--all-files-available](https://cloud.githubusercontent.com/assets/2133/15965602/e7151626-2eec-11e6-8c2f-16e9ec2a4567.png)
If one or more files are on tape in Bendo:
![curatend-298--download-delay-notice](https://cloud.githubusercontent.com/assets/2133/15965612/f2fbc7be-2eec-11e6-910b-f2a74f225acd.png)
Tooltip with delay prompt:
![curatend-298--download-delay-tooltip](https://cloud.githubusercontent.com/assets/2133/15965622/03dad570-2eed-11e6-9c31-e1ae249613da.png)
The recall item page looks like:
![curatend-298--recall-file-page](https://cloud.githubusercontent.com/assets/2133/15965794/00206494-2eee-11e6-9112-ad45e510835b.png)
When the item is cached in Bendo the file starts downloading.

**Comment by ruthtillman** [comment]
I am on board with all of this. If people want tweaks later, we can tweak later, but this is certainly suitable to deploy. Thanks, Dan.

**Comment by dbrower** [comment]
I like it.

On the retrieving page could the text "This operation could take some time" be changed to read

> Retrieving the file may take several minutes. The download will start automatically when the file is ready.

**Comment by danhorst** [comment]
@dbrower explained to me that files above a certain size are _never_ cached by Bendo to prevent cache thrashing. The existing application behavior doesn’t accommodate this:
![curatend 298-file retrieval download logic](https://cloud.githubusercontent.com/assets/2133/16055592/fb6c6af6-323f-11e6-9901-e26acf7b4541.png)
