### ISSUE TITLE
DOI minting text unclear

### ISSUE THREAD

**Issue by dbrower** [ndlib/curate_nd#386]
The form to make a DOI says this: "Publisher (Required for DOI)". I read it to mean you can't have a DOI without a publisher, ergo your work must be published. Really, what it sounds like it means is, you must have a publisher (field completed) to have a DOI.

- [x] Decide on the desired text
- [ ] Make the change in the application

**Comment by danhorst** [comment]
@dbrower or @ruthtillman what should we say instead? This?

> Publisher (this field must be filled in to generate a DOI)

**Comment by ruthtillman** [comment]
@dbrower I'm not sure what you were thinking but perhaps something along the lines of "If publishing the materials on CurateND, you may designate the University of Notre Dame as Publisher"? -- disclaimer, brain slow because also paying attention to THATCamp so don't know how good that sentence is.

**Comment by dbrower** [comment]
This was a comment from Mandy. I haven't seen the form. If we are minting DOIs, should we just make the publisher always be "University of Notre Dame" since we will be pointing the DOI into Curate? I take "publisher" in this case to be whoever is making the content available to the internet.

Or, if that is a bad idea, having text text saying that for unpublished items enter "UND" the publisher?

@ruthtillman sentence surprisingly not bad.

**Comment by ruthtillman** [comment]
I don't know how our DOIs work, so are we always essentially the publisher if we're minting?

**Comment by danhorst** [comment]
@ruthtillman we support two methods of adding DOIs to works:
![screen shot 2016-04-22 at 10 38 23 am](https://cloud.githubusercontent.com/assets/2133/14744822/72f6e27a-0876-11e6-9d64-cd6d5e48e0d8.png)

**Scenario 1**
A patron is depositing a pre-print of a published article where the publisher created a DOI we allow them to attach the publisher

> should we just make the publisher always be "University of Notre Dame" since we will be pointing the DOI into Curate?

@dbrower I don’t think this is the case if we are re-using an existing DOI from another source. However, I don’t have strong opinions about this.

**Scenario 2**
A patron is depositing origional work with the intent of makeing it available to the general public through CurateND. If they request a DOI we can create one for the record in CurateND. The only metadata attribute that we _must_ provide to create a DOI is “publisher” (in addition to title which we already require).

**Comment by dbrower** [comment]
Here is the EZID doc on it: http://ezid.cdlib.org/doc/apidoc.html#profile-dc
(not sure if we are supplying datacite or DC metadata. doesn't really matter; they have the same guidance).

My interpretation is that we are always the publisher since we are hosting the files.

**Comment by dbrower** [comment]
@danhorst If we are reusing a DOI from another source then we are *not* the publisher. That is simply another identifier we attach to the work.

If we have an uploaded file and the user ALSO wants to generate a DOI to it, then we are the publisher since the DOI will point to us? Again, just my interpretation.

**Comment by ruthtillman** [comment]
Ok, I've identified the aspects of this problem that are making it tricky for me to have an easy answer and broken them down.

Problem in brief: We're requiring an extra behavior to get the DOI however all the DOIs are essentially assigned to Curate as the place where the DOI is published/points. This makes Curate at least _one_ publisher (I don't know how much we can consider DOIs to be profound statements about things).

My recommendation in brief: We remove the Publisher field submission from the process, change the help text slightly so that people know they can either put in a publisher DOI, or mint a new DOI that will point to Curate, or not make a DOI.

Recommendation broken down into steps: 

- New text: "Yes, I would like to create a DOI for this Article. (This DOI will point to your [Article]* on CurateND.)"
- Edit help text for Publisher: remove "(Required for DOI)"
- Edit what is actually sent to the DOI Minter -- this seems like the hardest part. Ideal behavior would be that a value of "CurateND" or "Notre Dame" or whatever you think is appropriate gets sent to the PID minter if this radio button is checked. This would not write/overwrite/affect any information about dc:publisher being submitted to descMetadata and would be completely divorced. How hard is this to do? Is this too difficult?

*I am assuming here that either the value is hardcoded or uses a variable in "for this Article", so whichever would be appropriate.

**Comment by danhorst** [comment]
@ruthtillman I like this statement of the problem. However because it is more than just a textual change it will not fit into our next release. It is a good candidate for a maintenance sprint item so I will classify it as such.

**Comment by ruthtillman** [comment]
Sounds good to me, yes. As I kept thinking, I realized it was really a
functional change.

**Comment by mhavert** [comment]
Don, from the example you have above, the greyed out DOI expression in the box for 'I already have a DOI' is a sample or model for the user, yes? When I was having difficulty with my deposit yesterday, I wondered if because I was indicating ND as my publisher and Curate as my repository if the DOI was already made and that was it. I think that this is just a standard example. I appreciate Ruth's recommendations and see that you'll all work them into a future release. Thanks.

**Comment by dbrower** [comment]
Could someone show @mhavert whenever this change is deployed to testing or preprod?
